/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  sb: [
    { type: 'autogenerated', dirName: '.' },
    {
      type: 'link',
      label: '📚 Examples',
      href: 'https://frontend-v3--63d9db6068cc34f24abb23a9.chromatic.com/',
    },
    {
      type: 'link',
      label: '📦 NPM',
      href: 'https://www.npmjs.com/package/@pinpoint-fe/scatter-chart/',
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
